baseurl = "http://localhost:63342/hugo_page/public/"
languageCode = "de-DE"
title = "Schutzgemeinschaft"

theme = "hugo-phlat-theme"

[[menu.header]]
    name = "Home"
    weight = 1
    url = "/"


[Social]
  facebook = "http://www.facebook.com/schutzgemeinschaft.110kvNEINDANKE"

[params]
    sidebartitle = "SG 110KV"
    sidebartagline = "Für eine SINNVOLLE Stromversorgung"
    authorlink = false
    socialsharing = true
    keywords = ["default", "keywords", "if", "no", "front", "matter"]
    description = "A description that will appear as a default if front matter does not exist"
    categories = ["Energie AG", "Bürgermeister"]
    favicon = "favicon.ico"
    google_analytics = "UA-5073886-1"
    subTitle = "für eine SINNVOLLE Stromversorgung"

[permalinks]
        post = "/:year/:month/:slug/"
        page = "/:slug/"

[taxonomies]
        tag = "tags"
        category = "categories"